<a href="https://colab.research.google.com/github/JairEsc/Mat_Apl/blob/main/matrices_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importamos la libreria de numpy, matplotlib.pyplot, linalg.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import   


podemos generar una secuencia de numeros: usando np.arange()

In [3]:
i=np.arange(-5,10,.5)
print(i)

[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5]


np.zeros(), np.ones() para matrices o vectores llenos de 0's o 1's.

np.eye() para matrices con 1's en la diagonal.

In [4]:
print(np.eye(2,3))

[[1. 0. 0.]
 [0. 1. 0.]]


matrices de valores aleatorios: np.random.rand()

In [7]:
print(np.random.rand(2,2))

[[0.62077651 0.69191489]
 [0.64030733 0.89566112]]


In [14]:
print(np.random.randint(5,size=(2,2)))

[[1 2]
 [2 1]]


np.dot(A,B)=A@B, B.T=np.traspose(B)

In [15]:
print(np.flip(np.array([1,2,3,4])))## Hace un cambio. Cuando la matriz es cuadrada coincide con la transpuesta.

[4 3 2 1]
