<a href="https://colab.research.google.com/github/JairEsc/Mat_Apl/blob/main/MN_T7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
import numpy as np
def factorizar_LU(matriz):
    n=len(matriz)
    L=np.zeros((n,n))
    U=np.zeros((n,n))
    for j in range(n):
        for i in range(j,n):
            sum=0
            for k in range(i):
                sum+=L[i][k]*U[k][j]
            L[i][j]=matriz[i][j]-sum
            
            if(i>j):
                sum=0
                for k in range(j):
                    sum+=L[j][k]*U[k][i]
                U[j][i]=(matriz[j][i]-sum)/L[j][j]
            else: U[i][j]=1  
            
    return([L,U])

In [146]:
def cholesky_LDLt(matriz):
    n=len(matriz)
    L=np.zeros((n,n))
    D=np.zeros(n)
    for j in range(n):
        for i in range(j,n):
            print('j,i',j,i)
            if(i==j):
                sum=0
                for k in range(j):
                    sum+=D[k]*L[j][k]**2
                D[j]=matriz[i][j]-sum  
                L[i][j]=1
            else:
                sum=0
                for k in range(j):
                    sum+=L[i][k]*L[j][k]*D[k]
                    print(L[i][k],'*',L[j][k],'*',D[k])
                L[i][j]=(matriz[i][j]-sum)/(D[j])         
            print('L:',L)
            print('D:',D)
    return ([L,D])
   

In [147]:
matriz=[
[8, 2, 9],
[4, 9, 4],
[6, 7, 9]]
L,D=cholesky_LDLt(matriz)
print(L.T)
print(np.diag(D))
np.dot(L,np.dot(np.diag(D),L.T))

j,i 0 0
L: [[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
D: [8. 0. 0.]
j,i 0 1
L: [[1.  0.  0. ]
 [0.5 0.  0. ]
 [0.  0.  0. ]]
D: [8. 0. 0.]
j,i 0 2
L: [[1.   0.   0.  ]
 [0.5  0.   0.  ]
 [0.75 0.   0.  ]]
D: [8. 0. 0.]
j,i 1 1
L: [[1.   0.   0.  ]
 [0.5  1.   0.  ]
 [0.75 0.   0.  ]]
D: [8. 7. 0.]
j,i 1 2
0.75 * 0.5 * 8.0
L: [[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [0.75       0.57142857 0.        ]]
D: [8. 7. 0.]
j,i 2 2
L: [[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [0.75       0.57142857 1.        ]]
D: [8.         7.         2.21428571]
[[1.         0.5        0.75      ]
 [0.         1.         0.57142857]
 [0.         0.         1.        ]]
[[8.         0.         0.        ]
 [0.         7.         0.        ]
 [0.         0.         2.21428571]]


array([[8., 4., 6.],
       [4., 9., 7.],
       [6., 7., 9.]])

In [87]:
matriz=[
[8, 2, 9],
[4, 9, 4],
[6, 7, 9]]
L,U=factorizar_LU(matriz)
n=len(matriz)

print('L:',L)
print(U)
np.dot(L,U)

L: [[8.      0.      0.     ]
 [4.      8.      0.     ]
 [6.      5.5     2.59375]]
[[ 1.      0.25    1.125 ]
 [ 0.      1.     -0.0625]
 [ 0.      0.      1.    ]]


array([[8., 2., 9.],
       [4., 9., 4.],
       [6., 7., 9.]])

In [93]:
import scipy.linalg
scipy.linalg.cho_factor()

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]), array([[1.    , 0.    , 0.    ],
        [0.5   , 1.    , 0.    ],
        [0.75  , 0.6875, 1.    ]]), array([[ 8.     ,  2.     ,  9.     ],
        [ 0.     ,  8.     , -0.5    ],
        [ 0.     ,  0.     ,  2.59375]]))