<a href="https://colab.research.google.com/github/JairEsc/Mat_Apl/blob/main/MN_T7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
def factorizar_LU(matriz):
    n=len(matriz)
    L=np.zeros((n,n))
    U=np.zeros((n,n))
    for j in range(n):
        for i in range(j,n):
            sum=0
            for k in range(i):
                sum+=L[i][k]*U[k][j]
            L[i][j]=matriz[i][j]-sum
            
            if(i>j):
                sum=0
                for k in range(j):
                    sum+=L[j][k]*U[k][i]
                U[j][i]=(matriz[j][i]-sum)/L[j][j]
            else: 
                U[i][j]=1 
                if(L[i][i]==0):
                    return("Error en la construcción de L")
    return([L,U])

In [2]:
def superior(list,b):
  n=len(list)
  X=[b[n-1]/list[n-1][n-1]]
  X_inv=[X[0]]
  for i in range(1,n):#len(list) es el número de renglones de la matriz
    acum=0
    for j in range(i):#0<=j<=i-1 
      acum+=X[j]*list[n-i-1][n-1-j]
    X.append((b[n-1-i]-acum)/list[n-1-i][n-1-i])
    X_inv.insert(0,X[i])
  return X_inv
def inferior(list,b):#list debe contener las entradas de la matriz triangular.
#Será aceptable introducir un arreglo de arreglos de distintos tamaños, para solo introducir las entradas no cero.
  X=[b[0]/list[0][0]]
  for i in range(1,len(list)):#len(list) es el número de renglones de la matriz
    acum=0
    for j in range(i):#0<=j<=i-1 
      acum+=X[j]*list[i][j]
    X.append((b[i]-acum)/list[i][i])
  return X

In [3]:
print("Ejercicio 1, Matriz 100x100\n")
m1=np.loadtxt("M_LARGE.txt",skiprows=1)
b1=np.loadtxt("V_LARGE.txt",skiprows=1)
L_m,U_m=factorizar_LU(m1)#Descomposición
np.linalg.norm(np.dot(L_m,U_m)-m1)#Verificar la descomposición
y=inferior(L_m,b1)#Resolver Ly=b
x=superior(U_m,y)#Resolver Ux=y
print("Distancia entre las soluciones: ",np.linalg.norm(x-np.linalg.solve(m1,b1)))

Ejercicio 1, Matriz 100x100

Distancia entre las soluciones:  2.7571896676106323e-14


In [4]:
print("Ejercicio 2, Matriz 4x4\n")
m2=np.loadtxt("M_SMALL.txt",skiprows=1)
#b2=np.loadtxt("V_SMALL.txt",skiprows=1)
print(factorizar_LU(m2))
print(m2[1][1]-m2[1][0]*m2[0][1]/m2[0][0])#Esto explica el error en la construcción.


Ejercicio 2, Matriz 4x4

Error en la construcción de L
0.0


In [5]:
def cholesky_LDLt(matriz):
    n=len(matriz)
    L=np.zeros((n,n))
    D=np.zeros(n)
    for j in range(n):
        for i in range(j,n):
            if(i==j):
                sum=0
                for k in range(j):
                    sum+=D[k]*L[j][k]**2
                D[j]=matriz[i][j]-sum  
                L[i][j]=1
            else:
                sum=0
                for k in range(j):
                    sum+=L[i][k]*L[j][k]*D[k]
                L[i][j]=(matriz[i][j]-sum)/(D[j])         
    return ([L,D])
   

In [6]:
from scipy import linalg
linalg.lu(m2)

(array([[1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.46610111,  1.        ,  0.        ,  0.        ],
        [ 0.30886266,  0.62082104,  1.        ,  0.        ],
        [ 0.5       , -0.        , -0.        ,  1.        ]]),
 array([[ 2.40282200e+00,  4.42523200e+00,  1.92937400e+00,
          1.37035500e+00],
        [ 0.00000000e+00, -1.09791854e+00,  1.15388864e+00,
         -7.21499858e-02],
        [ 0.00000000e+00,  0.00000000e+00, -7.45695939e-01,
          1.31836874e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          5.00000000e-07]]))

In [8]:
print("Ejercicio 3, Matriz Tridiagonal \n")

N=[4,50,100]#Tamaños
n=N[0]
tri_diag=np.zeros((n,n))
for j in range(n):#Llenado de la matriz
    if j==0:
        tri_diag[j][j]=2
        tri_diag[j][j+1]=-1
    if j==n-1:
        tri_diag[j][j-1]=-1
        tri_diag[j][j]=2
    if (j>0):
        if(j<n-1):
            tri_diag[j][j]=2
            tri_diag[j][j+1]=-1
            tri_diag[j][j-1]=-1
L,D=cholesky_LDLt(tri_diag)#Descomposición
D=np.diag(D)#La función regresa un arreglo con las entradas de la diagonal, no una matriz.
fo = open(f"L_"+str(n)+".txt", "w")
np.savetxt(fo, L, fmt='%1.2e', comments='')
fo1 = open(f"D_"+str(n)+".txt", "w")
np.savetxt(fo1, D, fmt='%1.2e', comments='')
fo2 = open(f"LT_"+str(n)+".txt", "w")
np.savetxt(fo2, L.T, fmt='%1.2e', comments='') 
fo.close()
fo1.close()
fo2.close()

np.dot(L,np.dot(np.diag(D),L.T))#Verificar la descomposición. 

Ejercicio 3, Matriz Tridiagonal 



array([ 2.00000000e+00, -5.00000000e-01,  1.66533454e-16, -5.55111512e-17])