<a href="https://colab.research.google.com/github/JairEsc/Mat_Apl/blob/main/MN_T8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
def check_diag_dom(matriz):
    n=len(matriz)
    diago_dom=True
    for i in range(n):
        sum=0
        for j in range(n):
            sum+=matriz[i][j]
        if(2*matriz[i][i]<sum):
            diago_dom=False;
            break;
    return (diago_dom)

In [4]:
import math
def dist_rel(x,y):#x=(x_1,x_2,...x_n), y=(y_1,y_2,...y_n)
    numerador=0
    denominador=0
    for i in range(len(x)):
        numerador+=(x[i]-y[i])**2
        denominador+=(x[i])**2
    return(math.sqrt(numerador/denominador))

In [125]:
import numpy as np
def Jacobi(matriz,b,tol=10**(-6),max_iter=100,**x_0,):
    if(not check_diag_dom(matriz)): 
        return("la matriz no es diagonalmente dominante")
    else:
        count=0
        n=len(matriz)
        if(x_0):
            x_0=x_0['x_0']
            x_1=np.zeros(n)
        else:
            x_0=np.zeros(n)
            x_1=np.zeros(n)
        print(matriz)
        print(b)
        while(count<=max_iter):
            count+=1
            for i in range(n):
                sum=0
                for j in range(n):
                    if(j!=i):
                        sum+=matriz[i][j]*x_0[j]
                x_1[i]=(b[i]-sum)/matriz[i][i]
            if(np.linalg.norm(np.array(x_1)-np.array(x_0))<tol):
                print("numero de iteraciones: ",count)
                return (x_1)
            else:
                x_0=x_1
                x_1=np.zeros(n)
        

In [131]:
def Gauss_Seidel(matriz,b,tol=10**(-6),max_iter=100,**x_0,):
    if(not check_diag_dom(matriz)): 
        return("la matriz no es diagonalmente dominante")
    else:
        count=0
        n=len(matriz)
        if(x_0):
            x_0=x_0['x_0']
        else:
            x_0=np.zeros(n)
        print(matriz)
        print(b)
        while(count<=max_iter):
            count+=1
            x_1=np.copy(x_0)
            for i in range(n):
                sum=0
                for j in range(n):
                    if(j!=i):
                        sum+=matriz[i][j]*x_0[j]
                x_0[i]=(b[i]-sum)/matriz[i][i]
            if(np.linalg.norm(np.array(x_1)-np.array(x_0))<tol):
                print("numero de iteraciones: ",count)
                return (x_0)
            

In [126]:
matriz=[[10,2,1],[1,5,1],[2,3,10]]
b=[7,-8,6]
tol=0.05
x_0=[0.1,-1.7,0.9]
Jacobi(matriz,b,tol=10**(-3),x_0=x_0)

[[10, 2, 1], [1, 5, 1], [2, 3, 10]]
[7, -8, 6]
numero de iteraciones:  8


array([ 0.99989363, -2.00012224,  0.99984466])

In [130]:
matriz=[[10,2,1],[1,5,1],[2,3,10]]
b=[7,-8,6]
tol=0.05
x_0=[0.1,-1.7,0.9]
Gauss_Seidel(matriz,b,tol=10**(-3),x_0=x_0)

[[10, 2, 1], [1, 5, 1], [2, 3, 10]]
[7, -8, 6]
[ 0.1 -1.7  0.9] [0.95, -1.7, 0.9]
[ 0.1 -1.7  0.9] [0.95, -1.97, 0.9]
[ 0.1 -1.7  0.9] [0.95, -1.97, 1.001]
[ 0.95  -1.97   1.001] [0.9939, -1.97, 1.001]
[ 0.95  -1.97   1.001] [0.9939, -1.99898, 1.001]
[ 0.95  -1.97   1.001] [0.9939, -1.99898, 1.000914]
[ 0.9939   -1.99898   1.000914] [0.9997046, -1.99898, 1.000914]
[ 0.9939   -1.99898   1.000914] [0.9997046, -2.00012372, 1.000914]
[ 0.9939   -1.99898   1.000914] [0.9997046, -2.00012372, 1.0000961959999999]
[ 0.9997046  -2.00012372  1.0000962 ] [1.0000151244, -2.00012372, 1.0000961959999999]
[ 0.9997046  -2.00012372  1.0000962 ] [1.0000151244, -2.00002226408, 1.0000961959999999]
[ 0.9997046  -2.00012372  1.0000962 ] [1.0000151244, -2.00002226408, 1.000003654344]
numero de iteraciones:  4


[1.0000151244, -2.00002226408, 1.000003654344]

In [30]:
x_0=np.zeros(3)
x_0

array([0., 0., 0.])

In [ ]:
A=[[-0.1,1000,-1000],[-1000,0.1,1000],[-1000,1000,0.1]]
check_diag_dom(A)

False