<a href="https://colab.research.google.com/github/JairEsc/Mat_Apl/blob/main/MN_T7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
def factorizar_LU(matriz):
    n=len(matriz)
    L=np.zeros_like(matriz)
    U=np.zeros_like(matriz)
    for m in range(n):
        U[m][m]=1
    for j in range(n):
        for i in range(j):
            sum=0
            for k in range(i):
                sum+=L[i][k]*U[k][j]
            U[i][j]=(matriz[i][j]-sum)/L[i][i]
        for i in range(j,n):
            sum=0
            for k in range(j):
                sum+=L[i][k]*U[k][j]
            L[i][j]=matriz[i][j]-sum
        
    return([L,U])

In [24]:
matriz=[
[8, 2, 9],
[4, 9, 4],
[6, 7, 9]]
L,U=factorizar_LU(matriz)
print(L,'\n \n',U)
n=len(matriz)

print('L:',L)
print(U)
np.dot(L,U)

[[8 0 0]
 [4 9 0]
 [6 7 3]] 
 
 [[1 0 1]
 [0 1 0]
 [0 0 1]]
L: [[8 0 0]
 [4 9 0]
 [6 7 3]]
[[1 0 1]
 [0 1 0]
 [0 0 1]]


array([[8, 0, 8],
       [4, 9, 4],
       [6, 7, 9]])

In [12]:
for k in range(1):
    print(k)

0
