<a href="https://colab.research.google.com/github/JairEsc/Mat_Apl/blob/main/MN_T7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
def factorizar_LU(matriz):
    n=len(matriz)
    L=np.zeros((n,n))
    U=np.zeros((n,n))
    for j in range(n):
        for i in range(j,n):
            sum=0
            for k in range(i):
                sum+=L[i][k]*U[k][j]
            L[i][j]=matriz[i][j]-sum
            
            if(i>j):
                sum=0
                for k in range(j):
                    sum+=L[j][k]*U[k][i]
                U[j][i]=(matriz[j][i]-sum)/L[j][j]
            else: U[i][j]=1  
            
    return([L,U])

In [8]:
def cholesky_LDLt(matriz):
    n=len(matriz)
    L=np.zeros((n,n))
    D=np.zeros(n)
    for j in range(n):
        for i in range(j,n):
            if(i==j):
                sum=0
                for k in range(j):
                    sum+=D[k]*L[j][k]**2
                D[j]=matriz[i][j]-sum  
                L[i][j]=1
            else:
                sum=0
                for k in range(j):
                    sum+=L[i][k]*L[j][k]*D[k]
                L[i][j]=(matriz[i][j]-sum)/(D[j])         
    return ([L,D])
   

In [14]:
m1=np.loadtxt("M_LARGE.txt",skiprows=1)
b1=np.loadtxt("V_LARGE.txt",skiprows=1)
L_m,U_m=factorizar_LU(m1)
np.linalg.norm(np.dot(L_m,U_m)-m1)

1.830595838894773e-13

In [20]:
m2=np.loadtxt("M_SMALL.txt",skiprows=1)
b2=np.loadtxt("V_SMALL.txt",skiprows=1)
L_m2,U_m2=factorizar_LU(m2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: divide by zero encountered in double_scalars
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in double_scalars


In [18]:
from scipy import linalg
linalg.lu(m2)

(array([[1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.46610111,  1.        ,  0.        ,  0.        ],
        [ 0.30886266,  0.62082104,  1.        ,  0.        ],
        [ 0.5       , -0.        , -0.        ,  1.        ]]),
 array([[ 2.40282200e+00,  4.42523200e+00,  1.92937400e+00,
          1.37035500e+00],
        [ 0.00000000e+00, -1.09791854e+00,  1.15388864e+00,
         -7.21499858e-02],
        [ 0.00000000e+00,  0.00000000e+00, -7.45695939e-01,
          1.31836874e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          5.00000000e-07]]))

In [49]:
N=[4,50,100]
n=N[0]
tri_diag=np.zeros((n,n))
print(tri_diag)
for j in range(n):
    print(j)
    if j==0:
        tri_diag[j][j]=2
        tri_diag[j][j+1]=-1
    if j==n-1:
        tri_diag[j][j-1]=-1
        tri_diag[j][j]=2
    if (j>0 & j<3):
        print(j<3)
        tri_diag[j][j]=2
        tri_diag[j][j+1]=-1
        tri_diag[j][j-1]=-1
    print(tri_diag)
print(tri_diag)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
0
[[ 2. -1.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
1
True
[[ 2. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
2
True
[[ 2. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0.  0.  0.]]
3
False


IndexError: ignored