<a href="https://colab.research.google.com/github/JairEsc/Mat_Apl/blob/main/MN_T10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def check_diag(A,tol,pr=False):#Pensado para matrices simetricas
    boolean=True
    breaker=False
    for i in range(len(A)):
        for j in range(i,len(A)):
            if(i!=j):
                if(abs(A[i][j])>tol):
                    boolean=False;
                    breaker=True;
                    break;
        if(breaker==True):
            break
    return(boolean)
def entrada_max(A):#Regresa una lista [i,j], tal que a_{i,j} es el valor maximo en valor absoluto.
#Pensado para matrices simetricas
    max=abs(A[0][1])
    index=[0,1]
    for i in range(len(A)):
        for j in range(i,len(A[0])):
            if(i!=j):
                if(max<abs(A[i][j])):
                    max=abs(A[i][j])
                    index=i,j
    return(index)
import numpy as np


In [28]:
def Jacobi_rot(A,tol,max_Iter):
    count=0
    n=len(A)
    P=np.identity(n)
    while((check_diag(A,tol)==False)&(count<=max_Iter)):
        p,q=entrada_max(A)
        a=A[p][q]
        if(A[p][p]==A[q][q]):
            theta=np.pi/4
        else:
            theta=0.5*np.arctan(2*a/(A[p][p]-A[q][q]))
        #Ya tenemos la rotacion y podemos hacer el producto de matrices
        R=np.identity(n)
        R[p][p]=np.cos(theta)
        R[p][q]=-np.sin(theta)
        R[q][p]=-R[p][q]
        R[q][q]=R[p][p]
        A=np.dot(R.T,np.dot(A,R))#Se puede mejorar, modificando solo aquellas entradas que cambian.
        count+=1
        P=np.dot(P,R)
    if(count>max_Iter):
        print("Maxima iteracion alcanzada")
    else:
        print("num. Iteraciones: ", str(count))
    return(P,np.diagonal(A))

In [42]:
A_1=np.loadtxt("Eigen_3x3.txt",skiprows=1);
print("Matriz 3x3:\n")
print(A_1)
P,D=Jacobi_rot(A_1,10**(-5),max_Iter=1000)
A_1=np.loadtxt("Eigen_3x3.txt",skiprows=1);
print("\nVerificación:    A=P*D*P.T\n")
print(np.dot(np.dot(P,np.diag(D)),P.T))

Matriz 3x3:

[[ 3.  -0.1 -0.2]
 [-0.1  7.  -0.3]
 [-0.2 -0.3 10. ]]
num. Iteraciones:  5

Verificación:    A=P*D*P.T

[[ 2.99999999 -0.0999999  -0.19999999]
 [-0.0999999   7.00000001 -0.3       ]
 [-0.19999999 -0.3        10.        ]]


In [35]:
A_1=np.loadtxt("Eigen_125x125.txt",skiprows=1);
#print(A_1)
P,D=Jacobi_rot(A_1,10**(-5),max_Iter=1000)
A_1=np.loadtxt("Eigen_125x125.txt",skiprows=1);
print("Maxima diferencia entre mi resultado y la matriz original:\n")
print(np.max(A_1-np.dot(np.dot(P,np.diag(D)),P.T)))

num. Iteraciones:  833
Maxima diferencia entre mi resultado y la matriz original:

1.750280971793163e-05


Maxima diferencia entre mi resultado y la matriz original:

1.750280971793163e-05


In [ ]:
check_diag(A_1,tol=0.001,pr=True)

8.28507489964143


False