<a href="https://colab.research.google.com/github/JairEsc/Mat_Apl/blob/main/MN_T9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math
def max_eigen(A,tol,max_iter,**v_0):
    n=len(A)
    if(v_0):#Es opcional
        v_0=v_0['v_0']
    else:#Se toma el vector de 1's.
        v_0=(np.zeros(n)+1/math.sqrt(n))#Normalizado
    v_1=np.dot(A,v_0)#iteracion
    lambda_0=np.dot(v_0,v_1)
    lambda_1=np.sqrt(np.dot(v_1,v_1))#se toma raíz para poder compararlos
    count=0
    while((abs(lambda_0-lambda_1)>tol)&(count<max_iter)):
        count+=1
        v_0=v_1/np.linalg.norm(v_1)#Normalizacion
        v_1=np.dot(A,v_0)#iteracion
        lambda_0=lambda_1
        lambda_1=np.dot(v_0,v_1)
    if(count>max_iter):
        return("Maxima iteracion alcanzada")
    else:
        print("numero de iteraciones: "+str(count))
        return([lambda_1,v_1])

In [2]:
tol=10**(-6)
max_iter=100
A=[[0,2],[2,3]]
max_eigen(A,tol=tol,max_iter=max_iter,v_0=[1,1])

numero de iteraciones: 6


[3.999999966886309, array([1.78878159, 3.57774515])]

In [3]:
import numpy as np
def factorizar_LU(matriz):
    n=len(matriz)
    L=np.zeros((n,n))
    U=np.zeros((n,n))
    for j in range(n):
        for i in range(j,n):
            sum=0
            for k in range(i):
                sum+=L[i][k]*U[k][j]
            L[i][j]=matriz[i][j]-sum
            if(i>j):
                sum=0
                for k in range(j):
                    sum+=L[j][k]*U[k][i]
                U[j][i]=(matriz[j][i]-sum)/L[j][j]
            else: 
                U[i][j]=1 
                if(L[i][i]==0):
                    return("Error en la construcción de L")
    return([L,U])
def superior(list,b):
  n=len(list)
  X=[b[n-1]/list[n-1][n-1]]
  X_inv=[X[0]]
  for i in range(1,n):#len(list) es el número de renglones de la matriz
    acum=0
    for j in range(i):#0<=j<=i-1 
      acum+=X[j]*list[n-i-1][n-1-j]
    X.append((b[n-1-i]-acum)/list[n-1-i][n-1-i])
    X_inv.insert(0,X[i])
  return X_inv
def inferior(list,b):#list debe contener las entradas de la matriz triangular.
#Será aceptable introducir un arreglo de arreglos de distintos tamaños, para solo introducir las entradas no cero.
  X=[b[0]/list[0][0]]
  for i in range(1,len(list)):#len(list) es el número de renglones de la matriz
    acum=0
    for j in range(i):#0<=j<=i-1 
      acum+=X[j]*list[i][j]
    X.append((b[i]-acum)/list[i][i])
  return X
def solve(L_m,U_m,b):
    y=inferior(L_m,b)#Resolver Ly=b
    return(superior(U_m,y))#Resolver Ux=y

In [4]:
import numpy as np
import math
def min_eigen(A,tol,max_iter,**v_0):
    n=len(A)
    if(v_0):#Es opcional
        v_0=v_0['v_0']
    else:#Se toma el vector de 1's.
        v_0=(np.zeros(n)+1/math.sqrt(n))#Normalizado
    L,U=factorizar_LU(A)
    v_1=solve(L,U,v_0)#Se resuelve el sistema
    lambda_0=np.dot(v_0,v_1)
    lambda_1=np.sqrt(np.dot(v_1,v_1))#se toma raíz para poder compararlos
    count=0
    while((abs(lambda_0-lambda_1)>tol)&(count<max_iter)):
        count+=1
        v_0=v_1/np.linalg.norm(v_1)#Se normaliza
        v_1=solve(L_m=L,U_m=U,b=v_0)#iteracion
        lambda_0=lambda_1
        lambda_1=np.dot(v_0,v_1)
    if(count>=max_iter):
        return("Maxima iteracion alcanzada")
    else:
        print("numero de iteraciones: "+str(count))
        return([1/lambda_1,v_1])

In [5]:
print("Matriz 3x3\n")
A_1=np.loadtxt("Eigen_3x3.txt",skiprows=1);
min=min_eigen(A_1,tol,max_iter)
print("Eigenvalor menor: ", min[0])
print("Asociado a ", min[1]/np.linalg.norm(min[1]))
print("Verificación con Numpy")
print("Eigenvalor menor: ",np.min(np.linalg.eig(A_1)[0]))

print("\nMatriz 50x50\n")
A_2=np.loadtxt("Eigen_50x50.txt",skiprows=1);
min=min_eigen(A_2,tol,max_iter)
print("Eigenvalor menor: ", min[0])
print("Asociado a ", min[1]/np.linalg.norm(min[1]))
print("Verificación con Numpy")
print("Eigenvalor menor: ",np.min(np.linalg.eig(A_2)[0]))

print("\nMatriz 125x125\n")
A_3=np.loadtxt("Eigen_125x125.txt",skiprows=1);
min=min_eigen(A_3,tol,max_iter)
print("Eigenvalor menor: ", min[0])
#print("Asociado a ", min[1]/np.linalg.norm(min[1]))
print("Verificación con Numpy")
print("Eigenvalor menor: ",np.min(np.linalg.eig(A_3)[0]))

Matriz 3x3

numero de iteraciones: 9
Eigenvalor menor:  2.9913437401709206
Asociado a  [0.99918442 0.02735707 0.02970007]
Verificación con Numpy
Eigenvalor menor:  2.9913433225920967

Matriz 50x50



OSError: ignored

In [19]:
print("Matriz 3x3\n")
A_1=np.loadtxt("Eigen_3x3.txt",skiprows=1);
max=max_eigen(A_1,tol,max_iter)
print("Eigenvalor mayor: ", max[0])
print("Asociado a ", max[1]/np.linalg.norm(max[1]))
print("Verificación con Numpy")
print("Eigenvalor mayor: ",np.max(np.linalg.eig(A_1)[0]))

print("\nMatriz 50x50\n")
A_2=np.loadtxt("Eigen_50x50.txt",skiprows=1);
max=max_eigen(A_2,tol,max_iter)
print("Eigenvalor mayor: ", max[0])
print("Asociado a ", max[1]/np.linalg.norm(max[1]))
print("Verificación con Numpy")
print("Eigenvalor mayor: ",np.max(np.linalg.eig(A_2)[0]))

print("\nMatriz 125x125\n")
A_3=np.loadtxt("Eigen_125x125.txt",skiprows=1);
max=max_eigen(A_3,tol,max_iter)
print("Eigenvalor mayor: ", max[0])
#print("Asociado a ", min[1]/np.linalg.norm(min[1]))
print("Verificación con Numpy")
print("Eigenvalor mayor: ",np.max(np.linalg.eig(A_3)[0]))

Matriz 3x3

numero de iteraciones: 22
Eigenvalor mayor:  10.034795757490057
Asociado a  [-0.02690747 -0.09717924  0.9949031 ]
Verificación con Numpy
Eigenvalor mayor:  10.034796264113933

Matriz 50x50



OSError: ignored

In [23]:

m=3
L=[]
V=[]
A=np.copy(A_1)
for i in range(m):
    print(A)
    max=max_eigen(A,tol=10**(-6),max_iter=100)
    L.append(max[0])
    V.append(max[1]/np.linalg.norm(max[1]))
    A=deflacion(A,L[i],V[i])
print(A)


[[ 3.  -0.1 -0.2]
 [-0.1  7.  -0.3]
 [-0.2 -0.3 10. ]]
numero de iteraciones: 22
[[ 2.99273469 -0.12623946  0.06863475]
 [-0.12623946  6.90523335  0.67020345]
 [ 0.06863475  0.67020345  0.0672362 ]]
numero de iteraciones: 10
[[2.98654211e+00 8.05159112e-02 8.86366139e-02]
 [8.05159112e-02 2.17077556e-03 2.38960046e-03]
 [8.86366139e-02 2.38960046e-03 2.63077146e-03]]
numero de iteraciones: 2
[[ 2.00081729e-10 -2.55184721e-09 -4.42354191e-09]
 [-2.55184721e-09  1.00530325e-07 -5.33743117e-09]
 [-4.42354191e-09 -5.33743139e-09  1.53896240e-07]]


In [24]:
print(L)
print(V)
print(np.linalg.eig(A_1))
print(A_1)

[10.034795757490057, 6.973860590111664, 2.991343397771632]
[array([-0.02690747, -0.09717924,  0.9949031 ]), array([-0.02979883,  0.9949111 ,  0.09624937]), array([0.99919715, 0.02693793, 0.02965485])]
(array([ 2.99134332, 10.03479626,  6.97386041]), array([[-0.9991909 , -0.02689902,  0.02989969],
       [-0.02714665, -0.09746053, -0.99486909],
       [-0.02967504,  0.99487582, -0.09665145]]))
[[ 3.  -0.1 -0.2]
 [-0.1  7.  -0.3]
 [-0.2 -0.3 10. ]]


In [12]:
def deflacion(A,l,v):
    for i in range(len(A)):
        for j in range(len(A[0])):
            A[i][j]-=l*v[i]*v[j]
    return(A)