<a href="https://colab.research.google.com/github/JairEsc/Mat_Apl/blob/main/MN_T7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
def factorizar_LU(matriz):
    n=len(matriz)
    L=np.zeros((n,n))
    U=np.zeros((n,n))
    for j in range(n):
        for i in range(j,n):
            sum=0
            for k in range(i):
                sum+=L[i][k]*U[k][j]
            L[i][j]=matriz[i][j]-sum
            
            if(i>j):
                sum=0
                for k in range(j):
                    sum+=L[j][k]*U[k][i]
                U[j][i]=(matriz[j][i]-sum)/L[j][j]
            else: 
                U[i][j]=1 
                if(L[i][i]==0):
                    return("")
    return([L,U])

In [11]:
def superior(list,b):
  n=len(list)
  X=[b[n-1]/list[n-1][n-1]]
  X_inv=[X[0]]
  for i in range(1,n):#len(list) es el número de renglones de la matriz
    acum=0
    for j in range(i):#0<=j<=i-1 
      acum+=X[j]*list[n-i-1][n-1-j]
    X.append((b[n-1-i]-acum)/list[n-1-i][n-1-i])
    X_inv.insert(0,X[i])
  return X_inv
def inferior(list,b):#list debe contener las entradas de la matriz triangular.
#Será aceptable introducir un arreglo de arreglos de distintos tamaños, para solo introducir las entradas no cero.
  X=[b[0]/list[0][0]]
  for i in range(1,len(list)):#len(list) es el número de renglones de la matriz
    acum=0
    for j in range(i):#0<=j<=i-1 
      acum+=X[j]*list[i][j]
    X.append((b[i]-acum)/list[i][i])
  return X

In [10]:
m2=np.loadtxt("M_SMALL.txt",skiprows=1)
#b2=np.loadtxt("V_SMALL.txt",skiprows=1)
factorizar_LU(m2)

''

In [16]:
m1=np.loadtxt("M_LARGE.txt",skiprows=1)
b1=np.loadtxt("V_LARGE.txt",skiprows=1)
L_m,U_m=factorizar_LU(m1)
np.linalg.norm(np.dot(L_m,U_m)-m1)
y=inferior(L_m,b1)
x=superior(U_m,y)
print(np.linalg.norm(x-np.linalg.solve(m1,b1)))

2.7571896676106323e-14


In [ ]:
def cholesky_LDLt(matriz):
    n=len(matriz)
    L=np.zeros((n,n))
    D=np.zeros(n)
    for j in range(n):
        for i in range(j,n):
            if(i==j):
                sum=0
                for k in range(j):
                    sum+=D[k]*L[j][k]**2
                D[j]=matriz[i][j]-sum  
                L[i][j]=1
            else:
                sum=0
                for k in range(j):
                    sum+=L[i][k]*L[j][k]*D[k]
                L[i][j]=(matriz[i][j]-sum)/(D[j])         
    return ([L,D])
   

In [ ]:
from scipy import linalg
linalg.lu(m2)

(array([[1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.46610111,  1.        ,  0.        ,  0.        ],
        [ 0.30886266,  0.62082104,  1.        ,  0.        ],
        [ 0.5       , -0.        , -0.        ,  1.        ]]),
 array([[ 2.40282200e+00,  4.42523200e+00,  1.92937400e+00,
          1.37035500e+00],
        [ 0.00000000e+00, -1.09791854e+00,  1.15388864e+00,
         -7.21499858e-02],
        [ 0.00000000e+00,  0.00000000e+00, -7.45695939e-01,
          1.31836874e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          5.00000000e-07]]))

In [ ]:
N=[4,50,100]
n=N[1]
tri_diag=np.zeros((n,n))
for j in range(n):
    if j==0:
        tri_diag[j][j]=2
        tri_diag[j][j+1]=-1
    if j==n-1:
        tri_diag[j][j-1]=-1
        tri_diag[j][j]=2
    if (j>0):
        if(j<n-1):
            tri_diag[j][j]=2
            tri_diag[j][j+1]=-1
            tri_diag[j][j-1]=-1
L,D=cholesky_LDLt(tri_diag)
print(L)
print(D)

np.dot(L,np.dot(D,L.T))

[[ 1.          0.          0.         ...  0.          0.
   0.        ]
 [-0.5         1.          0.         ...  0.          0.
   0.        ]
 [ 0.         -0.66666667  1.         ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  1.          0.
   0.        ]
 [ 0.          0.          0.         ... -0.97959184  1.
   0.        ]
 [ 0.          0.          0.         ...  0.         -0.98
   1.        ]]
[2.         1.5        1.33333333 1.25       1.2        1.16666667
 1.14285714 1.125      1.11111111 1.1        1.09090909 1.08333333
 1.07692308 1.07142857 1.06666667 1.0625     1.05882353 1.05555556
 1.05263158 1.05       1.04761905 1.04545455 1.04347826 1.04166667
 1.04       1.03846154 1.03703704 1.03571429 1.03448276 1.03333333
 1.03225806 1.03125    1.03030303 1.02941176 1.02857143 1.02777778
 1.02702703 1.02631579 1.02564103 1.025      1.02439024 1.02380952
 1.02325581 1.02272727 1.02222222 1.02173913 1.0212766  1.02083333
 1.02040816 1.02  

array([ 2.00000000e+00, -5.00000000e-01,  1.66533454e-16, -5.55111512e-17,
       -2.77555756e-16,  5.55111512e-17,  5.55111512e-17,  5.55111512e-17,
        5.55111512e-17,  5.55111512e-17, -1.52655666e-16,  0.00000000e+00,
        1.38777878e-17,  2.35922393e-16,  4.16333634e-17,  2.63677968e-16,
       -1.59594560e-16,  4.16333634e-17,  2.77555756e-16, -1.87350135e-16,
        3.46944695e-17,  1.52655666e-16,  2.70616862e-16,  1.59594560e-16,
        2.08166817e-17,  1.04083409e-16, -9.02056208e-17, -2.77555756e-17,
        1.38777878e-17, -1.52655666e-16,  1.11022302e-16,  1.66533454e-16,
       -1.07552856e-16, -5.55111512e-17,  2.42861287e-17,  2.08166817e-17,
       -1.59594560e-16,  1.45716772e-16, -1.59594560e-16,  1.04083409e-17,
        1.17961196e-16,  1.28369537e-16,  1.42247325e-16, -4.16333634e-17,
       -4.16333634e-17, -2.53269627e-16,  5.20417043e-17,  1.38777878e-17,
        1.04083409e-16,  2.30408096e-16])