<a href="https://colab.research.google.com/github/JairEsc/Mat_Apl/blob/main/MN_T11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [ ]:
#metodo de rayleigh

In [54]:
#metodo de iteracion en subespacio.
def gen_base_ortogonal(m,n):
    base=[]
    for j in range(m):
        b=[0]*n
        b[j]=1
        base.append(np.array(b))
    return np.array(base)
def factorizar_LU(matriz):#Codigo reciclado: Factorizacion LU
    n=len(matriz)
    L=np.zeros((n,n))
    U=np.zeros((n,n))
    for j in range(n):
        for i in range(j,n):
            sum=0
            for k in range(i):
                sum+=L[i][k]*U[k][j]
            L[i][j]=matriz[i][j]-sum
            if(i>j):
                sum=0
                for k in range(j):
                    sum+=L[j][k]*U[k][i]
                U[j][i]=(matriz[j][i]-sum)/L[j][j]
            else: 
                U[i][j]=1 
                if(L[i][i]==0):
                    print("Error en la construcción de L")
    return([L,U])

def superior(list,b):#Codigo reciclado:Resolver sistema triangular
  n=len(list)
  X=[b[n-1]/list[n-1][n-1]]
  X_inv=[X[0]]
  for i in range(1,n):#len(list) es el número de renglones de la matriz
    acum=0
    for j in range(i):#0<=j<=i-1 
      acum+=X[j]*list[n-i-1][n-1-j]
    X.append((b[n-1-i]-acum)/list[n-1-i][n-1-i])
    X_inv.insert(0,X[i])
  return X_inv

#Codigo reciclado:Resolver sistema triangular
def inferior(list,b):#list debe contener las entradas de la matriz triangular.
#Será aceptable introducir un arreglo de arreglos de distintos tamaños, para solo introducir las entradas no cero.
  X=[b[0]/list[0][0]]
  for i in range(1,len(list)):#len(list) es el número de renglones de la matriz
    acum=0
    for j in range(i):#0<=j<=i-1 
      acum+=X[j]*list[i][j]
    X.append((b[i]-acum)/list[i][i])
  return X
def solve(L_m,U_m,b):
    y=inferior(L_m,b)#Resolver Ly=b
    return(superior(U_m,y))#Resolver Ux=y
def check_diag(A,tol):#Pensado para matrices en general (NO simetricas)
    boolean=True
    breaker=False
    for i in range(len(A)):
        for j in range(i,len(A)):
            if(i!=j):
                if(abs(A[i][j])>tol):
                    boolean=False;
                    breaker=True;
                    break;
        if(breaker==True):
            break
    return(boolean)
def Jacobi_rot(A,tol,max_Iter,pr=True):
    count=0
    n=len(A)
    P=np.identity(n)
    while((check_diag(A,tol)==False)&(count<=max_Iter)):
        p,q=entrada_max(A)
        a=A[p][q]
        if(A[p][p]==A[q][q]):
            theta=np.pi/4
        else:
            theta=0.5*np.arctan(2*a/(A[p][p]-A[q][q]))
        #Ya tenemos la rotacion y podemos hacer el producto de matrices
        R=np.identity(n)
        R[p][p]=np.cos(theta)
        R[p][q]=-np.sin(theta)
        R[q][p]=-R[p][q]
        R[q][q]=R[p][p]
        A=np.dot(R.T,np.dot(A,R))#Se puede mejorar, modificando solo aquellas entradas que cambian.
        count+=1
        P=np.dot(P,R)
    if(count>max_Iter):
        print("Maxima iteracion alcanzada")
    else:
        if(pr==True):
            print("num. Iteraciones: ", str(count))
    return(P,np.diagonal(A))
def entrada_max(A):#Regresa una lista [i,j], tal que a_{i,j} es el valor maximo en valor absoluto.
#Pensado para matrices simetricas
    max=abs(A[0][1])
    index=[0,1]
    for i in range(len(A)):
        for j in range(i,len(A[0])):
            if(i!=j):
                if(max<abs(A[i][j])):
                    max=abs(A[i][j])
                    index=i,j
    return(index)
def min_eigen(A,tol,max_iter,pr=True,v_0=[]):
    n=len(A)
    if(len(v_0)==0):#Es opcional
        v_0=(np.zeros(n)+1/math.sqrt(n))#Normalizado
    L,U=factorizar_LU(A)
    v_1=solve(L,U,v_0)#Se resuelve el sistema
    lambda_0=np.dot(v_0,v_1)
    lambda_1=np.sqrt(np.dot(v_1,v_1))#se toma raíz para poder compararlos
    count=0
    while((abs(lambda_0-lambda_1)>tol)&(count<max_iter)):
        count+=1
        v_0=v_1/np.linalg.norm(v_1)#Se normaliza
        v_1=solve(L_m=L,U_m=U,b=v_0)#iteracion
        lambda_0=lambda_1
        lambda_1=np.dot(v_0,v_1)
    if(count>=max_iter):
        return("Maxima iteracion alcanzada")
    else:
        if(pr==True):
            print("numero de iteraciones: "+str(count))
        return([1/lambda_1,v_1])

In [ ]:
##Algoritmo
##1 Genera subconjunto ortonormal.
## Usa ese vector inicial (con deflación para conservar la ortogonalidad) para UNA iteración de potencia inversa (o potencia.) 
#-> eso genera una nueva matriz \Phi de approximaciones de vectores. Se normalizan. Estos nuevos vectores no necesariamente son ortogonales (solo cuando A sea ortogonal).
## Hacer el producto B=\Phi.T*A*\Phi. Parar cuando esto sea diagonal.
## Aplicar Jacobi (Completo) sobre B.
#-> Genera un producto de matrices de rotacion Q, que puedo usar para actualizar.\Phi=\Phi_old*Q.
##Repetir

In [ ]:
def quitar_contribucion(v_0,list_eigen):
    if list_eigen==[]:
        print("no se quito nada")
        return(np.array(v_0))
    else:
        aux=v_0
        for v in list_eigen:
            v_0-=np.dot(aux,np.array(v))*np.array(v)
        print("se quitaron: ",list_eigen)
        return v_0


In [ ]:
np.dot([[2,0],[0,2]],np.array([1,2]))

array([2, 4])

In [84]:
def Iter_subespacio(A,m,tol=0.0000001,max_iter=4000):
    #1 Generar subconjunto ortonormal.
    phi_old=[np.array([1.0,0.0,0.0]),np.array([0.0,1.0,0.0])]
    print(phi_old)
    for i in range(3):
        phi_new=[]
        for j in range(m):
            v_i=np.array(phi_old[j])
            if(j==0):#no hay deflacion
                v_i_next=np.linalg.solve(A,v_i)
                phi_new.append(v_i_next/np.linalg.norm(v_i_next))
            else:
                aux=v_i
                for k in range(j):#Si hay deflacion
                    v_i-=np.dot(np.array(aux),np.array(phi_new[k]))*np.array(phi_new[k])
                v_i_next=np.linalg.solve(A,v_i)
                phi_new.append(v_i_next/np.linalg.norm(v_i_next))
        B=np.dot(np.array(phi_new),np.dot(A,np.array(phi_new).T)).T
        print("B:",B)
        phi_old=np.dot(np.array(phi_new).T,Jacobi_rot(A=B,tol=tol,max_Iter=max_iter,pr=False)[0]).T
        print("product", np.dot(phi_old,np.dot(A,np.array(phi_old).T)))

In [85]:
A=[[4,3,12],[3,10,13],[12,13,50]]
Iter_subespacio(A,m=2)


[array([1., 0., 0.]), array([0., 1., 0.])]
B: [[ 1.05433978e+00  1.18752712e-17]
 [-2.83915837e-16  6.20251279e+00]]
product [[ 1.05433978e+00 -2.83915837e-16]
 [ 1.18752712e-17  6.20251279e+00]]
B: [[ 1.05179600e+00  4.25061572e-16]
 [-6.13349825e-17  6.19816909e+00]]
product [[ 1.05179600e+00 -6.13349825e-17]
 [ 4.25061572e-16  6.19816909e+00]]
B: [[1.05175292e+00 1.13880955e-17]
 [3.33632079e-16 6.19907152e+00]]
product [[1.05175292e+00 3.33632079e-16]
 [1.13880955e-17 6.19907152e+00]]


In [48]:
np.linalg.eig([[4,3,12],[3,10,13],[12,13,50]])

(array([56.74913984,  1.05175165,  6.19910851]),
 array([[ 0.22812092,  0.96865129,  0.09836429],
        [ 0.27441092,  0.03296734, -0.96104724],
        [ 0.93416245, -0.24622721,  0.25828796]]))

In [12]:
#np.dot([ 0.92098861 , 0.03134517, -0.23411155],np.dot([[4,3,12],[3,10,13],[12,13,50]],[ 0.92098861 , 0.03134517, -0.23411155]))
np.linalg.norm(np.dot([[4,3,12],[3,10,13],[12,13,50]],[-0.09727447,  0.96234605, -0.25382625])-0.95*np.array([-0.09727447,  0.96234605, -0.25382625]))


5.255800913724584