<a href="https://colab.research.google.com/github/JairEsc/Mat_Apl/blob/main/MN_T12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [30]:
#Factorizacion QR
def QR(A):
    n=len(A);
    Q=np.zeros((n,n))
    R=np.zeros((n,n))
    R[0,0]=np.linalg.norm(A[:,0])
    Q[:,0]=A[:,0]/np.linalg.norm(A[:,0])
    # A_k=r_{1l}*q_1+\cdots+ r_{kk}*q_{k} entonces r_{ik}=q_{i} \cdot a_{k}
    #q_{k}=(a_k-\sum^{k-1} r_{ik}*q_{i})/norma.
    for k in range(1,n):
        a_star=np.array(A[:,k])
        for i in range(k):
            R[i,k]=np.dot(Q[:,i],A[:,k])
            a_star=np.subtract(a_star,R[i,k]*Q[:,i])
        Q[:,k]=a_star/np.linalg.norm(a_star)
        R[k,k]=np.linalg.norm(a_star)
    return(Q,R)

In [31]:
A=np.array([[1,1,1],[0,5,2],[-1,2,1]])
Q,R=QR(A)
print(np.dot(Q,R))

[[ 1.  1.  1.]
 [ 0.  5.  2.]
 [-1.  2.  1.]]
