<a href="https://colab.research.google.com/github/JairEsc/Mat_Apl/blob/main/MN_T7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
import numpy as np
def factorizar_LU(matriz):
    n=len(matriz)
    L=np.zeros((n,n))
    U=np.zeros((n,n))
    for j in range(n):
        for i in range(j,n):
            sum=0
            for k in range(i):
                sum+=L[i][k]*U[k][j]
            L[i][j]=matriz[i][j]-sum
            
            if(i>j):
                sum=0
                for k in range(j):
                    sum+=L[j][k]*U[k][i]
                U[j][i]=(matriz[j][i]-sum)/L[j][j]
            else: U[i][j]=1  
            
    return([L,U])

In [ ]:
def cholesky_LDLt(matriz):
    n=len(matriz)
    L=np.zeros((n,n))
    D=np.zeros(n)
    for i in range(n):
        for j in range(n):
            if(i=j):
                sum=0
                for k in range(j):
                    sum+=matriz[i][j]-D[k]*L[i][j]**2
                D[i]=
            else:
                sum=0
                for k in range(j):
                    sum+=L[i][k]*L[j][k]*D[k]
                L[i][j]=(matriz[i][j]-sum)/L[j][j]
    return ([L,D])
   

In [87]:
matriz=[
[8, 2, 9],
[4, 9, 4],
[6, 7, 9]]
L,U=factorizar_LU(matriz)
n=len(matriz)

print('L:',L)
print(U)
np.dot(L,U)

L: [[8.      0.      0.     ]
 [4.      8.      0.     ]
 [6.      5.5     2.59375]]
[[ 1.      0.25    1.125 ]
 [ 0.      1.     -0.0625]
 [ 0.      0.      1.    ]]


array([[8., 2., 9.],
       [4., 9., 4.],
       [6., 7., 9.]])

In [34]:
import scipy.linalg
scipy.linalg.lu(matriz,)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]), array([[1.    , 0.    , 0.    ],
        [0.5   , 1.    , 0.    ],
        [0.75  , 0.6875, 1.    ]]), array([[ 8.     ,  2.     ,  9.     ],
        [ 0.     ,  8.     , -0.5    ],
        [ 0.     ,  0.     ,  2.59375]]))