<a href="https://colab.research.google.com/github/JairEsc/Mat_Apl/blob/main/Opt_T4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
#steepest descent.
def Steepest_descent(alpha,x_0,f,grad_f,tol_grad=10**(-4),max_iter=10**5):
    x_1=x_0-alpha*np.array(grad_f(x_0))
    x_0=x_1
    k=1
    while(np.linalg.norm(grad_f(x_1))>tol_grad and k<max_iter):
        k+=1
        x_1=x_0-alpha*np.array(grad_f(x_0))
        x_0=x_1
    
    if(k==max_iter):
        return "F"
    else:
        print(k,"numero de iteraciones")
        return (x_1)

In [ ]:
def Rosembrok(X):#X es un vector.
    suma=0
    for i in range(len(X)-1):
        suma+=100*((X[i+1]-X[i]**2)**2)+(1-X[i])**2
    return (suma)
def Rosembrok_grad(X):
    D=[]
    D.append(-400*(X[0]*(X[1]-X[0]**2))-2*(1-X[0]))
    for i in range(1,len(X)-1):
        D.append(-400*(X[i]*(X[i+1]-X[i]**2))+200*(X[i]-X[i-1]**2)-2*(1-X[i]))
    D.append(200*(X[-1]-X[-2]**2))
    return D
def Rosembrok_Hessian(X):
    M=[]
    #Renglon 1
    D=np.zeros(len(X))
    D[0]=(-400*(X[1]-X[0]**2)+800*(X[0]**2)+2)
    D[1]=-400*(X[1])
    M.append(D)
    #Renglon 2<i<n
    for i in range(1,len(X)-1):
        D=np.zeros(len(X))
        D[i]=(-400*(X[i+1]-X[i]**2)+800*(X[i]**2)+202)
        D[i-1]=-400*X[i-1]
        D[i+1]=-400*X[i]
        M.append(D)
    #Renglon n
    D=np.zeros(len(X))
    D[-2]=-400*X[-2]
    D[-1]=200
    M.append(D)
    return M

In [ ]:
Rosembrok_Hessian([1,1,1])

[array([ 802., -400.,    0.]),
 array([-400., 1002., -400.]),
 array([   0., -400.,  200.])]

In [ ]:
def Wood(X):
    return (100*(X[0]**2-X[1])**2+(X[0]-1)**2+(X[2]-1)**2+90*(X[2]**2-X[3])**2+10.1*((X[1]-1)**2+(X[3]-1)**2)+19.8*(X[1]-1)*(X[3]-1))
def Wood_grad(X):
    G=[]
    G.append(400*X[0]*(X[0]**2-X[1])+2*(X[0]-1))
    G.append(-200*(X[0]**2-X[1])+20.2*(X[1]-1)+19.8*(X[3]-1))
    G.append(2*(X[2]-1)+360*(X[2]**2-X[3])*X[2])
    G.append(-180*(X[2]**2-X[3])+20.2*(X[3]-1)+19.8*(X[1]-1))
    return G
def Wood_Hessian(X):
    D1=[2+400*(X[0]**2-1)+800*X[0]**2,-400*X[0],0,0]
    D2=[-400*X[0],220.2,0,19.8]
    D3=[0,0,2+720*(X[2]**2)+360*(X[2]-X[3]),-360*X[2]]
    D4=[0,19.8,-360*X[2],200.2]
    return [D1,D2,D3,D4]


In [42]:
def f_normal(X,l,Y):
    n=len(X)
    suma=0
    for i in range(n-1):
        suma+=(X[i]-Y[-1])**2+l*(X[i+1]-X[i])**2
    suma+=(X[-1]-Y[-1])**2
    return suma
def gen_y(s,n,pr='False'):
    etha=np.random.normal(0,s,size=n)
    t=[]
    y=[]
    for i in range(n-1):
        t.append(((2/(n-1))*(i)-1))
        y.append((t[-1]**2+etha[i]))
    t.append(1)
    y.append((t[-1]**2+etha[i]))
    if(pr=='True'):
        print(t)
        print(y)
        plt.plot(t,y)
    return (y)

def f_normal_grad(X,l,Y):
    D=[]
    D.append(2*(X[0]-Y[0])-2*l*(X[1]-X[0]))
    for i in range(1,len(X)-1):
        D.append(2*(X[i]-Y[i])-2*l*(X[i+1]-X[i])+2*l*(X[i]-X[i-1]))
    D.append(2*(X[-1]-Y[-1])-2*l*(X[-1]-X[-2]))
    return D
def f_normal_Hessian(X):##
    M=[]
    #Renglon 1
    D=np.zeros(len(X))
    D[0]=(-400*(X[1]-X[0]**2)+800*(X[0]**2)+2)
    D[1]=-400*(X[1])
    M.append(D)
    #Renglon 2<i<n
    for i in range(1,len(X)-1):
        D=np.zeros(len(X))
        D[i]=(-400*(X[i+1]-X[i]**2)+800*(X[i]**2)+202)
        D[i-1]=-400*X[i-1]
        D[i+1]=-400*X[i]
        M.append(D)
    #Renglon n
    D=np.zeros(len(X))
    D[-2]=-400*X[-2]
    D[-1]=200
    M.append(D)
    return M

In [44]:
f_normal([1,1,1,1,1,1,1,1,1,1,1,1,1],1.5,gen_y(0.01,13))

0.006553465499182995

In [ ]:
Wood_Hessian([1,1,1,1])

[[802, -400, 0, 0],
 [-400, 220.2, 0, 19.8],
 [0, 0, 722, -360],
 [0, 19.8, -360, 200.2]]

In [ ]:
print(Steepest_descent(alpha=0.001,x_0=[1.5,1.6],f=Rosembrok,grad_f=Rosembrok_grad))

20832 numero de iteraciones
[1.0001118  1.00022405]


In [ ]:
def Newton(x_0,f,grad_f,Hess_f,tol_grad=10**(-4)):
    d=np.linalg.solve(Hess_f(x_0[0],x_0[1]),-np.array(grad_f(x_0[0],x_0[1])))
    x_1=x_0+d
    x_0=x_1
    k=1
    while(np.linalg.norm(grad_f(x_1[0],x_1[1]))>tol_grad):
        k+=1
        d=np.linalg.solve(Hess_f(x_0[0],x_0[1]),-np.array(grad_f(x_0[0],x_0[1])))
        x_1=x_0+d
        x_0=x_1
    print(k,"iter")
    return (x_1)

In [ ]:
def Hess_f(x_1,x_2):
    return ([[-400*(x_2-x_1**2)+800*x_1**2+2,-400*x_1],[400*x_1,200]])

In [ ]:
Newton(x_0=[1.57,1.6],f=f,grad_f=grad_f,Hess_f=Hess_f)

7965 iter


array([1.00009997, 1.00020046])