<a href="https://colab.research.google.com/github/JairEsc/Mat_Apl/blob/main/Opt_T4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np

In [45]:
#steepest descent.
def Steepest_descent(alpha,x_0,f,grad_f,tol_grad=10**(-4),max_iter=10**5):
    x_1=x_0-alpha*np.array(grad_f(x_0))
    x_0=x_1
    k=1
    while(np.linalg.norm(grad_f(x_1))>tol_grad and k<max_iter):
        k+=1
        x_1=x_0-alpha*np.array(grad_f(x_0))
        x_0=x_1
    
    if(k==max_iter):
        return "F"
    else:
        print(k,"numero de iteraciones")
        return (x_1)

In [52]:
def Rosembrok(X):#X es un vector.
    suma=0
    for i in range(len(X)-1):
        suma+=100*((X[i+1]-X[i]**2)**2)+(1-X[i])**2
    return (suma)
def Rosembrok_grad(X):
    D=[]
    D.append(-400*(X[0]*(X[1]-X[0]**2))-2*(1-X[0]))
    for i in range(1,len(X)-1):
        D.append(-400*(X[i]*(X[i+1]-X[i]**2))+200*(X[i]-X[i-1]**2)-2*(1-X[i]))
    D.append(200*(X[-1]-X[-2]**2))
    return D
def Rosembrok_Hessian(X):
    M=[]
    #Renglon 1
    D=np.zeros(len(X))
    D[0]=(-400*(X[1]-X[0]**2)+800*(X[0]**2)+2)
    D[1]=-400*(X[1])
    M.append(D)
    #Renglon 2<i<n
    for i in range(1,len(X)-1):
        D=np.zeros(len(X))
        D[i]=(-400*(X[i+1]-X[i]**2)+800*(X[i]**2)+202)
        D[i-1]=-400*X[i-1]
        D[i+1]=-400*X[i]
        M.append(D)
    #Renglon n
    D=np.zeros(len(X))
    D[-2]=-400*X[-2]
    D[-1]=200
    M.append(D)
    return M

In [53]:
Rosembrok_Hessian([1,1,1])

[array([ 802., -400.,    0.]),
 array([-400., 1002., -400.]),
 array([   0., -400.,  200.])]

In [47]:
print(Steepest_descent(alpha=0.001,x_0=[1.5,1.6],f=Rosembrok,grad_f=Rosembrok_grad))

20832 numero de iteraciones
[1.0001118  1.00022405]


In [48]:
def Newton(x_0,f,grad_f,Hess_f,tol_grad=10**(-4)):
    d=np.linalg.solve(Hess_f(x_0[0],x_0[1]),-np.array(grad_f(x_0[0],x_0[1])))
    x_1=x_0+d
    x_0=x_1
    k=1
    while(np.linalg.norm(grad_f(x_1[0],x_1[1]))>tol_grad):
        k+=1
        d=np.linalg.solve(Hess_f(x_0[0],x_0[1]),-np.array(grad_f(x_0[0],x_0[1])))
        x_1=x_0+d
        x_0=x_1
    print(k,"iter")
    return (x_1)

In [49]:
def Hess_f(x_1,x_2):
    return ([[-400*(x_2-x_1**2)+800*x_1**2+2,-400*x_1],[400*x_1,200]])

In [50]:
Newton(x_0=[1.57,1.6],f=f,grad_f=grad_f,Hess_f=Hess_f)

7965 iter


array([1.00009997, 1.00020046])